// diseño de frontend/src/app/components/ProductCard.tsx
import { Product } from '../types/product';

interface ProductCardProps {
  product: Product;
  onAddToCart: (product: Product) => void;
}

export function ProductCard({ product, onAddToCart }: ProductCardProps) {
  return (
    <article className="product-card bg-white rounded-lg shadow-md overflow-hidden transition-transform hover:scale-105">
      <img
        src={product.image}
        alt={product.name}
        className="w-full h-48 object-cover"
      />
      <div className="p-4">
        <h3 className="mb-2">{product.name}</h3>
        <p className="text-sm text-gray-600 mb-2">Categoría: {product.category}</p>
        <p className="mb-4">
          ${product.price.toLocaleString('es-CL')}
        </p>
        <button
          onClick={() => onAddToCart(product)}
          className="w-full bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700 transition-colors"
          aria-label={`Agregar ${product.name} al carrito`}
        >
          Agregar al carrito
        </button>
      </div>
    </article>
  );
}

// frontend/src/app/components/product-card/product-card.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Product } from '../../models/product';

@Component({
  selector: 'app-product-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './product-card.component.html',
  styleUrl: './product-card.component.css'
})
export class ProductCardComponent {
  @Input({ required: true }) product!: Product;
  @Output() add = new EventEmitter<Product>();
}

<article class="product-card">
  <img [src]="product.image" [alt]="product.name" />
  <div class="product-info">
    <h3>{{ product.name }}</h3>
    <p class="product-meta">Categoria: {{ product.category }}</p>
    <p class="product-price">${{ product.price.toLocaleString('es-CL') }}</p>
    <button
      class="btn btn-primary"
      type="button"
      (click)="add.emit(product)"
      [attr.aria-label]="'Agregar ' + product.name + ' al carrito'"
    >
      Agregar al carrito
    </button>
  </div>
</article>
